# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://youik.cn
date_format: "ordinal"
title: Youik
subtitle: "摔倒了,爬起来就好"
description: "Dreams"
keywords: "Ing.."
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/Youik/youik.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: "Ing.."
organization: YOUIK, Inc.
organization_url: http://youik.cn
location: ShenZhen, China
email: "Ing.."

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge

collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: Youik
#douban_username: OriginNet
#facebook_username: OriginNet
#weibo_username: OriginNet
zhihu_username: Ing..
#twitter_username: youik

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: Youik
disqus_username: Youik
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
 #   analytics_id: UA-85602329-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Linux, Shell, Docker, Python, Golang, Kubernetes]
skill_mobile_app_keywords: [Linux]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: Youik/Youik.github.io

